name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy black isort flake8

      - name: Run pytest
        run: pytest tests

      - name: Run mypy
        run: mypy src/

      - name: Run black
        run: black --diff --check src/

      - name: Run isort
        run: isort --check-only src/

      - name: Run flake8
        run: flake8 src/
